version: "3"

networks:
  descrivizio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.98.64/29
          gateway: 192.168.98.70

services:
  descrivizio001:
    build: ./descrivizio001
    ports:
      - "7777:7777"
    networks:
      - descrivizio-network
    hostname: descrivizio001

  descrivizio001-api:
    build: ./descrivizio001-api
    ports:
      - "8085:8085"
    depends_on:
      - descrivizio001
    networks:
      - descrivizio-network
