apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: descrivizio001
spec:
  selector:
    matchLabels:
      app: descrivizio001
  template:
    metadata:
      labels:
        app: descrivizio001
    spec:
      containers:
        - name: web
          image: descrivizio001
          ressources:
            limits:
              cpu: "1"
              memory: "80Mi"
              nvidia.com/gpu: 1
          ports:
            - containerPort: 80
          args: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
          readinessProbe:
            httpPost:
              path: /model/descrivizio-001
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpPost:
              path: /model/descrivizio-001
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
